avatar link arguments
primer/view_components pull request #1006
Opened 2022-02-09 18:49 UTC by jamieshark

This PR adds an option for passing arguments directly to the rendered `a` tag in the Avatar component.

2022-02-09 19:12 UTC, camertron approved these changes

2022-03-01 17:32 UTC, jamieshark commented
Hey @camertron - not sure if there's something else I need to do to merge these changes, but seems like as a first-time contributor there are some checks that a maintainer has to do first?

2022-03-01 21:09 UTC, camertron requested changes
Hey @jamieshark, looks like a number of other changes were made here, so I've left a few additional comments 😄

2022-03-01 21:09 UTC, camertron commented on test/components/beta/avatar_test.rb
> +      assert_selector("img.avatar")
Is it just me or did this change from `refute_selector` to `assert_selector`, and if so, why? I don't see any HTML changes?

2022-03-01 21:09 UTC, camertron commented on app/components/primer/beta/avatar.rb
> +          (@link_arguments[:classes] ||= []) << "lh-0" # Addresses an overflow issue with linked avatars
I believe we usually do default classes like this in the constructor.

2022-03-01 21:09 UTC, camertron commented on app/components/primer/beta/avatar.rb
> +            render(Primer::BaseComponent.new(**@system_arguments)) { content }
Do we want to keep `.except(:classes)` here to maintain backwards compatibility?

2022-03-01 21:09 UTC, camertron commented on test/components/beta/avatar_test.rb
> +      assert_selector("img.avatar.circle")
Also wondering why this changed from `refute_selector` to `assert_selector` without accompanying HTML changes.

2022-03-16 20:59 UTC, jamieshark commented
I think I'm going to close this PR with changes for now since we have found a workaround on our end, and I am nervous to make these API changes to this component, but not others that render nested components. I can re-open in the future if this is a more widely adopted pattern!

2022-03-16 20:59 UTC, closed without merging