Add responsive values for `border` system argument
primer/view_components pull request #1829
Opened 2023-02-15 10:32 UTC by josepmartins

### Description

It's currently not possible to use responsive values for `border` even though the corresponding Primer CSS classes do exist: https://primer.style/design/foundations/css-utilities/borders#responsive-borders

Slack thread: https://github.slack.com/archives/CSGAVNZ19/p1676065040884579

<img width="1077" alt="Screenshot 2023-02-15 at 11 31 01" src="https://user-images.githubusercontent.com/912236/219002843-0cd97c4c-0489-4349-a45e-6d8f2d85f122.png">

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews

2023-02-16 10:27 UTC, josepmartins commented
> Hey @josepmartins, thanks for this! As it happens though, utilities.yml is generated by a rake task (`bundle exec rake utilities:build`). You'll need to modify it to include all the border stuff, otherwise your changes will get overwritten by the next run. For utilities that aren't well-suited to programmatic generation we use custom_utilities.yml, which is merged into the final result at the very end of `utilities:build`. It looks like custom_utilities.yml contains hard-coded entries for border classes, so we'll need to remove them and add the appropriate regex to `SUPPORTED_KEYS`.

@camertron thanks for reviewing it! ✨  I've tried adding the regex to the `SUPPORTED_KEYS` in the utilities, the problem is that generates a weird tree structure for borders. So the expected output for each border side [top, right, bottom, left] should be something like this:

```yml
:border_right:
  0:
     - border-right-0
     - border-sm-right-0
     - border-md-right-0
     - ... 
```


But instead, I'm getting this + the extra `:sm`, `:md`, `:lg` and `:xl`.

<img width="377" alt="Screenshot 2023-02-16 at 10 57 53" src="https://user-images.githubusercontent.com/912236/219332264-b8cdf233-d8ca-47ee-8f0f-938fe72785de.png">


I've ended up adding them to the `custom_utilities.yml` along with the missing responsive `border-radius` classes too, and updated the responsive classify tests to verify passing the arguments.

2023-02-17 04:30 UTC, camertron commented
@josepmartins ahh ok thanks for explaining!

2023-02-17 04:31 UTC, camertron requested changes

2023-02-17 04:31 UTC, camertron commented on lib/tasks/custom_utilities.yml
> -  "00":
What's up with all these indentation changes?

2023-03-17 17:25 UTC, camertron commented
Hey @josepmartins is this ready for another review?

2023-03-23 22:04 UTC, camertron approved these changes

2023-03-23 22:05 UTC, merged