Primer::Alpha::ActionBar component
primer/view_components pull request #1941
Opened 2023-04-07 17:23 UTC by jonrohan

### Description

Describe your changes here.

Closes # (type the issue number after # if applicable; otherwise remove this line)

### Integration

> Does this change require any updates to code in production?

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews

2023-04-14 17:38 UTC, camertron requested changes
Looking good! Just needs some tests 👍

2023-04-14 17:38 UTC, camertron commented on docs/src/@primer/gatsby-theme-doctocat/nav.yml
> +  - title: ActionBar - Fix my order in docs/src/@primer/gatsby-theme-doctocat/nav.yml
?

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +  min-width: calc(var(--primer-control-medium-size, 32px) * 3);
```suggestion
  min-width: calc(var(--control-medium-size) * 3); 
```

This took me awhile to understand. Maybe add a comment like "show minimum of 3 buttons"

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +  min-width: calc(var(--primer-control-small-size, 28px) * 3);
```suggestion
  min-width: calc(var(--control-small-size) * 3);
```

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +  min-width: calc(var(--primer-control-large-size, 40px) * 3);
```suggestion
  min-width: calc(var(--control-large-size) * 3);
```

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +  height: calc(var(--primer-control-medium-size, 32px) / 2);
```suggestion
  height: calc(var(--control-medium-size) / 2);
```

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +  margin: 0 var(--primer-controlStack-medium-gap-condensed, 8px);
```suggestion
  margin: 0 var(--controlStack-medium-gap-condensed);
```

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +  border-left: var(--primer-borderWidth-thin, 1px) solid var(--color-border-subtle);
```suggestion
  border-left: var(--borderWidth-thin) solid var(--color-border-subtle);
```

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +  margin: 0 var(--primer-controlStack-small-gap-condensed, 8px);
```suggestion
  margin: 0 var(--controlStack-small-gap-condensed);
```

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +  margin: 0 var(--primer-controlStack-large-gap-condensed, 8px);
```suggestion
  margin: 0 var(--controlStack-large-gap-condensed);
```

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +    gap: calc(var(--primer-control-minTarget-coarse, 44px) - var(--primer-control-medium-size, 32px)); /* 12px */
```suggestion
    gap: calc(var(--control-minTarget-coarse) - var(--control-medium-size)); /* 12px */
```

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +    gap: calc(var(--primer-control-minTarget-coarse, 44px) - var(--primer-control-small-size, 28px));  /* 16px */
```suggestion
    gap: calc(var(--control-minTarget-coarse) - var(--control-small-size));  /* 16px */
```

2023-07-05 23:14 UTC, langermank commented on app/components/primer/alpha/action_bar.pcss
> +    gap: calc(var(--primer-control-minTarget-coarse, 44px) - var(--primer-control-large-size, 40px));  /* 4px */
```suggestion
    gap: calc(var(--control-minTarget-coarse) - var(--control-large-size));  /* 4px */
```

2023-07-06 17:08 UTC, keithamus approved these changes

2023-07-06 18:44 UTC, langermank approved these changes

2023-07-06 18:44 UTC, langermank commented on app/components/primer/alpha/action_bar.html.erb
> +      <% menu.with_show_button(icon: :"kebab-horizontal", "aria-label": "Menu", size: @size, scheme: :invisible) %>
Just wondering if the aria-label should be a param that could be passed in by the consumer? Maybe with a default of "Menu"? I'm just not sure if that's something we may want to customize for accessibility.

2023-07-06 18:44 UTC, merged