Partially address a11y issues in Link component.
primer/view_components pull request #2034
Opened 2023-05-31 16:27 UTC by radglob

### Description

This PR partially addresses some of the concerns in https://github.com/github/primer/issues/1880.

It removes the option to render Links as `<span>`s and removes the negative `outline-offset` causing focus outlines to overlap with the first and last letters in the link text.

It does not fix issues with the Tooltip component (which is somewhat out of scope of the Link component), address color contrast issues in the dark-dimmed theme (this is something we're just not addressing at this time), or force links to show an underline at all times if surrounded by other text.

### Integration

> Does this change require any updates to code in production?

This will, as written, break usages of Link where the tag is set to `:span`. I'm not sure what the right way to deprecate this is in PVC. Happy to make that change if anyone can show me how to do that. I'm familiar with how this is handled in PRC.

### Merge checklist

- [X] Added/updated tests
- [X] Added/updated documentation
- [X] Added/updated previews

2023-05-31 23:02 UTC, camertron reviewed
Hey @radglob thanks for this 👍 Any idea how many places in dotcom are passing `tag: :span`?

2023-06-01 13:41 UTC, radglob commented
> Hey @radglob thanks for this 👍 Any idea how many places in dotcom are passing `tag: :span`?

@camertron Not sure how to check that. I've seen [this](https://musical-adventure-wlr3n3k.pages.github.io/?=s) for checking JS code. Is there something similar for checking Ruby stuff?

2023-06-01 17:32 UTC, camertron requested changes

2023-06-01 17:32 UTC, camertron commented on app/components/primer/beta/link.rb
> +        @system_arguments[:tag] = :a
Can we use the [`deny_tag_argument`](https://github.com/primer/view_components/blob/9829b632e1f6c16262377fa2c7e5dcb7bc4d929b/app/components/primer/component.rb#L133) helper here to raise an error if a tag is passed? That should prevent us having to write a linter, which I think is a bit overkill.

2023-06-01 17:55 UTC, radglob commented
> @radglob I usually just use VSCode's search feature in a Codespace. I just spun one up because I was curious and found only 3 usages, which isn't that many. Here's what I found:
> 
> 1. https://github.com/github/github/blob/1c1cfd98dfbf432ac0ce8255a2bb9f35cc6535d6/app/components/pages/protected_domains/domain_component.html.erb#L4
> 2. https://github.com/github/github/blob/1c1cfd98dfbf432ac0ce8255a2bb9f35cc6535d6/app/views/orgs/invitations/teams/_list.html.erb#L7
> 3. https://github.com/github/github/blob/1c1cfd98dfbf432ac0ce8255a2bb9f35cc6535d6/app/views/verifiable_domains/index.html.erb#L32
> 
> It would be great to have a plan for migrating these that you could include in the PR description under the "Integration" heading. We would need to potentially reach out to the teams who own these files and understand why they chose to use a `<span>` instead of an `<a>`.

I found three places in dotcom (the examples you have are for the Label component, not Link): https://github.com/github/github/blob/1c1cfd98dfbf432ac0ce8255a2bb9f35cc6535d6/app/views/code_navigation/_timed_out.html.erb#L9, https://github.com/github/github/blob/1c1cfd98dfbf432ac0ce8255a2bb9f35cc6535d6/app/views/code_navigation/_no_results.html.erb#L9, https://github.com/github/github/blob/1c1cfd98dfbf432ac0ce8255a2bb9f35cc6535d6/app/views/code_navigation/_results_backend.html.erb#L5.

I don't see anything obvious about these examples that would make the change a slow process. I imagine it was probably for stylistic reasons or something.

2023-06-01 18:19 UTC, camertron commented
Ah woops, sorry about that 😅 Ok cool! It would be great to verify that tho, just in case the team chose `<span>` for some specific reason. We could always make the change and then ask them to raise any objections during code review.

2023-06-21 20:32 UTC, jonrohan approved these changes

2023-06-21 20:58 UTC, camertron commented
Hey @radglob apologies for the slow response. Were you able to track down if changing any of the `<a>`s to `<span>`s is going to be problematic?

2023-07-10 15:46 UTC, merged