Add new button to dialog lookbook and remove whitespace:nowrap in but…
primer/view_components pull request #2514
Opened 2024-01-17 23:01 UTC by langermank

…ton css

_Authors: Please fill out this form carefully and completely._

_Reviewers: By approving this Pull Request you are approving the code change, as well as its deployment and mitigation plans._
_Please read this description carefully. If you feel there is anything unclear or missing, please ask for updates._

### What are you trying to accomplish?

### Screenshots

### Integration

#### List the issues that this change affects.

Closes # (type the GitHub issue number after #)

#### Risk Assessment
  

- [ ] **Low risk** the change is small, highly observable, and easily rolled back.
- [ ] **Medium risk** changes that are isolated, reduced in scope or could impact few users. The change will not impact library availability.
- [ ] **High risk** changes are those that could impact customers and SLOs, low or no test coverage, low observability, or slow to rollback.

### What approach did you choose and why?

### Anything you want to highlight for special attention from reviewers?

### Accessibility

- **Fixes axe scan violation** - This change fixes an existing [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation.
- **No new axe scan violation** - This change does not introduce any new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violations.
- **New axe violation** - This change introduces a new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation. Please describe why the violation cannot be resolved below.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Lookbook)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

2024-01-17 23:30 UTC, langermank commented on app/components/primer/beta/button.pcss
> +  padding-block: 'calc(var(--control-medium-paddingBlock) - 2px)',
```suggestion
  padding-block: calc(var(--control-medium-paddingBlock) - 2px);
```

2024-01-17 23:30 UTC, langermank commented on app/components/primer/beta/button.pcss
> +  align-self: 'stretch',
```suggestion
  align-self: stretch;
```

2024-01-18 17:44 UTC, camertron requested changes

2024-01-18 17:44 UTC, camertron commented on app/components/primer/beta/button.pcss
> +    padding-block: calc(var(--control-large-paddingBlock) - 2px),
```suggestion
    padding-block: calc(var(--control-large-paddingBlock) - 2px);
```

2024-01-18 20:45 UTC, langermank commented on app/components/primer/beta/button.pcss
> +  align-self: stretch;
```suggestion
  align-self: stretch;
  
```

2024-01-19 11:04 UTC, keithamus approved these changes

2024-01-19 17:40 UTC, camertron approved these changes

2024-01-22 23:19 UTC, merged