Add multiple body options to Overlay body slot
primer/view_components pull request #2781
Opened 2024-04-15 23:02 UTC by jonrohan

_Authors: Please fill out this form carefully and completely._

_Reviewers: By approving this Pull Request you are approving the code change, as well as its deployment and mitigation plans._
_Please read this description carefully. If you feel there is anything unclear or missing, please ask for updates._

### What are you trying to accomplish?

### Screenshots

### Integration

#### List the issues that this change affects.

Closes # (type the GitHub issue number after #)

#### Risk Assessment
  

- [ ] **Low risk** the change is small, highly observable, and easily rolled back.
- [ ] **Medium risk** changes that are isolated, reduced in scope or could impact few users. The change will not impact library availability.
- [ ] **High risk** changes are those that could impact customers and SLOs, low or no test coverage, low observability, or slow to rollback.

### What approach did you choose and why?

### Anything you want to highlight for special attention from reviewers?

### Accessibility

- **Fixes axe scan violation** - This change fixes an existing [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation.
- **No new axe scan violation** - This change does not introduce any new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violations.
- **New axe violation** - This change introduces a new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation. Please describe why the violation cannot be resolved below.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Lookbook)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

2024-04-15 23:12 UTC, jonrohan commented on app/components/primer/alpha/tab_panels.rb
> +      renders_many :tabs, lambda { |id: self.class.generate_id, selected: false, **system_arguments|
I updated this to auto generate one if it's not passed in. Didn't want to have to enforce making up an id for every selectpanel

2024-04-16 17:32 UTC, camertron requested changes

2024-04-16 17:32 UTC, camertron commented on app/components/primer/alpha/overlay.html.erb
> +      <% if bodies.size == 1 %>
I know visually it doesn't seem to matter, but can we handle the zero case here?

2024-04-19 20:35 UTC, camertron approved these changes
Nice 🎉

2024-04-19 21:06 UTC, merged